-- FB Burguer: comandas criadas antes do encaminhamento ao WhatsApp.
-- Uma comanda só conta como venda quando o administrador a fecha (status = completed).

alter table public.orders
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists whatsapp_redirected_at timestamptz,
  add column if not exists closed_at timestamptz,
  add column if not exists closed_by uuid references auth.users(id) on delete set null,
  add column if not exists cancelled_at timestamptz,
  add column if not exists admin_notes text;

create unique index if not exists idx_orders_order_number
  on public.orders(order_number);

create index if not exists idx_orders_business_closed
  on public.orders(business_id, closed_at desc)
  where status = 'completed';

create or replace function public.update_order_comanda(
  target_order_id uuid,
  new_customer_name text,
  new_customer_phone text,
  new_address_text text,
  new_payment_method text,
  new_notes text,
  new_admin_notes text,
  new_delivery_fee numeric,
  new_discount numeric,
  new_items jsonb
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.orders;
  item jsonb;
  new_subtotal numeric(10,2);
begin
  select * into current_order
  from public.orders
  where id = target_order_id
  for update;

  if current_order.id is null then
    raise exception 'Comanda não encontrada';
  end if;

  if not public.has_business_role(
    current_order.business_id,
    array['owner','manager']::public.business_role[]
  ) then
    raise exception 'Sem permissão para editar esta comanda';
  end if;

  if current_order.status <> 'pending' then
    raise exception 'Apenas comandas abertas podem ser editadas';
  end if;

  if new_payment_method not in ('pix', 'cash', 'card_on_delivery') then
    raise exception 'Forma de pagamento inválida';
  end if;

  if new_delivery_fee < 0 or new_discount < 0 then
    raise exception 'Taxa e desconto não podem ser negativos';
  end if;

  for item in select * from jsonb_array_elements(new_items)
  loop
    update public.order_items
    set
      quantity = greatest(1, least(100, (item->>'quantity')::integer)),
      unit_price = greatest(0, (item->>'unitPrice')::numeric),
      total = greatest(0, (item->>'unitPrice')::numeric)
        * greatest(1, least(100, (item->>'quantity')::integer))
    where id = (item->>'id')::uuid
      and order_id = target_order_id;
  end loop;

  select coalesce(sum(total), 0)
  into new_subtotal
  from public.order_items
  where order_id = target_order_id;

  update public.orders
  set
    customer_name = trim(new_customer_name),
    customer_phone = trim(new_customer_phone),
    address_text = trim(new_address_text),
    payment_method = new_payment_method,
    notes = nullif(trim(new_notes), ''),
    admin_notes = nullif(trim(new_admin_notes), ''),
    subtotal = new_subtotal,
    delivery_fee = new_delivery_fee,
    discount = new_discount,
    total = greatest(0, new_subtotal + new_delivery_fee - new_discount),
    updated_at = now()
  where id = target_order_id
  returning * into current_order;

  return current_order;
end;
$$;

create or replace function public.close_order_comanda(target_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.orders;
begin
  select * into current_order
  from public.orders
  where id = target_order_id
  for update;

  if current_order.id is null then
    raise exception 'Comanda não encontrada';
  end if;

  if not public.has_business_role(
    current_order.business_id,
    array['owner','manager']::public.business_role[]
  ) then
    raise exception 'Sem permissão para fechar esta comanda';
  end if;

  if current_order.status = 'cancelled' then
    raise exception 'Comanda cancelada não pode ser fechada';
  end if;

  update public.orders
  set
    status = 'completed',
    closed_at = coalesce(closed_at, now()),
    closed_by = auth.uid(),
    updated_at = now()
  where id = target_order_id
  returning * into current_order;

  return current_order;
end;
$$;

create or replace function public.cancel_order_comanda(target_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order public.orders;
begin
  select * into current_order
  from public.orders
  where id = target_order_id
  for update;

  if current_order.id is null then
    raise exception 'Comanda não encontrada';
  end if;

  if not public.has_business_role(
    current_order.business_id,
    array['owner','manager']::public.business_role[]
  ) then
    raise exception 'Sem permissão para cancelar esta comanda';
  end if;

  if current_order.status = 'completed' then
    raise exception 'Venda já confirmada. Não cancele sem reabrir a comanda.';
  end if;

  update public.orders
  set
    status = 'cancelled',
    cancelled_at = now(),
    updated_at = now()
  where id = target_order_id
  returning * into current_order;

  return current_order;
end;
$$;

grant execute on function public.update_order_comanda(uuid,text,text,text,text,text,text,numeric,numeric,jsonb) to authenticated;
grant execute on function public.close_order_comanda(uuid) to authenticated;
grant execute on function public.cancel_order_comanda(uuid) to authenticated;
